version: "3.5"

services:
  # Internet-connected reverse proxing web server
  caddy:
    build: ../caddy
    ports:
      - "80:80"
      - "443:443"
    # depends_on:
    volumes:
      - ~/docker-persistence/caddy:/data
      - ../caddy/Caddyfile:/etc/caddy/Caddyfile
      - ../../app/dist:/dist
      - ../caddy/test:/test