version: "3.5"

services:

  # vklass emulator generating dummy data
  vklass-dummy:
    image: python:3.9-slim-buster
    hostname: vklass-dummy
    container_name: vklass-dummy
    networks:
      default:
        ipv4_address: 172.18.1.20
    expose:
      - "12345"
    ports:
      - "12345:12345"
    volumes:
      - type: bind
        source: ./../vklass_dummy
        target: /host_volume
    environment:
      - FLASK_ENV=development
      - MORNING_UPDATE_HOUR=8
      - LATE_MORNING_UPDATE_HOUR=10
      - MAX_DAILY_ADDED_ABSENCES=50
    working_dir: /host_volume
    command: ./start.sh

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24
